version: '3.8'
services:
  backend: # run shell use - docker compose exec backend sh
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8005:5000 # Flask inside container 5000 outside 8005
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main # New name for service main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306